### ISSUE TITLE
Support Serverless v3

### ISSUE THREAD

**Issue by tomchiverton** [activescott/serverless-aws-static-file-handler#139]
https://github.com/activescott/serverless-aws-static-file-handler/blob/tom-httpApi-mine/package.json#L44

I don't think anything should break if this was just bumped .. .?

**Comment by tomchiverton** [comment]
I think this is the cause of https://github.com/serverless/serverless/issues/10863#issuecomment-1092888698

**Comment by tomchiverton** [comment]
And here's a branch to test with : https://github.com/tomchiverton/serverless-aws-static-file-handler/commit/6130b39fdce8ebf0b7ffb8bd3f20673609c166c9

As far as I can tell, it all works as intended, but doesn't add 30 meg to the deployment package.

**Comment by tomchiverton** [comment]
It might also be possible to work around with https://github.com/ACloudGuru/serverless-plugin-aws-alerts/pull/207#issuecomment-1098635212

**Comment by activescott** [comment]
@tomchiverton Thanks for driving this issue here. I am happy to bump it but interested to hear if there is a recommendation on removing the peerDependency altogether from the serverless team in serverless/serverless#10863 . Then lets solve this one way or the other. Always happy to review a PR too. The tests in the github actions in this repo should make sure it is pretty thoroughly tested.
