### ISSUE TITLE
Binary files using serverless-offline

### ISSUE THREAD

**Issue by chrisrothwell** [activescott/serverless-aws-static-file-handler#3]
Hi,
This project is perfect for me and I'm trying to get it to work using serverless-offline before publishing to AWS Lambda.
One thing I notice is that HTML files are served correctly with all appropriate headers, but Binary files return only the file (in base64 encoding I think) but without all the relevant headers (content-type etc.) so I cannot see the image in Postman / web browser etc. when invoking locally.
Is this an issue with serverless-offline, or is there some other reason why binary files are passed without headers?
Is there any trick I can do to test this locally, instead of deploying the whole thing every time?

Thanks so much!
Chris.

**Comment by activescott** [comment]
Thanks for letting me know @chrisrothwell ! 👍 

Looks like a bug. The binary support via API Gateway used to be non-trivial, but it looks like it has improved. I think the key part of the bug is at https://github.com/activescott/serverless-aws-static-file-handler/blob/master/StaticFileHandler.js#L141 - Note how if it is text it adds response headers, but if binary just returns the whole blob (without setting any headers).

As I mentioned, the binary support via API Gateway used to be wonky but [it looks like they have improved it](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html):
> If body is a binary blob, you can encode it as a Base64-encoded string and set isBase64Encoded to true. Otherwise, you can set it to false or leave it unspecified. 

So I think now, we could just have the binary code path return something more like the following instead:

```
let response = {
          statusCode: statusCode,
          headers: {
            'Content-Type': mimeType
          },
          isBase64Encoded: true,
          body: Buffer.from(stream).toString('base64')
}
```

Would you be up for submitting a pull request for this with an example and tests? If not, if you could create a very simple example repo demonstrating problem in a public github repo and reply here with a link, I'll use that to fix the issue, confirm it works with your test repo, and write some tests to make sure it stays stable.

**Comment by activescott** [comment]
I'm working on this issue...

**Comment by activescott** [comment]
This should now let you do what you want if you using Lambda Proxy Integration with the new 2.0.0-beta1 release. Get it from npm. Please feel free to re-open the issue if you have questions, concerns, or suggestions.

**Comment by chrisrothwell** [comment]
Hi, sorry, I just came back to this project and it seems to work great now :)

Chris.

**Comment by activescott** [comment]
Thanks for leaving a note @chrisrothwell !
