### ISSUE TITLE
2.0.2 -> 2.0.3 error message

### ISSUE THREAD

**Issue by katspaugh** [activescott/serverless-aws-static-file-handler#32]
After updating the NPM package from 2.0.2 to 2.0.3, the serverless command fails with this error:

```
Serverless plugin "serverless-aws-static-file-handler/plugins/BinaryMediaTypes" not found
```

When I downgrade back to 2.0.2, it goes away.

Is there any update needed for the config or might it be a regression bug?

**Comment by stgogm** [comment]
Found the same problem and noticed that the plugin has been moved to `src/plugins/BinaryMediaTypes`, so adding it as `'serverless-aws-static-file-handler/src/plugins/BinaryMediaTypes'` will make it work again.

**Comment by katspaugh** [comment]
Cool, thanks, @stgogm! I'll close this.

**Comment by activescott** [comment]
Thanks for reporting this @katspaugh and thanks for the quick action @stgogm. Looks like we broke this in #24 when most files where moved to the root, but not that plugin. A couple things I'll look into here:
1. [ ] Some e2e tests should have caught this :/
2. [ ] I wonder if we can publish a new version that works with either path since this was a breaking change and others are surely going to encounter it...

I'll take a quick look tonight...

**Comment by activescott** [comment]
@katspaugh and/or @stgogm I have created PR #34 that supports both paths for the plugin to prevent breaking anyone and it includes tests to confirm that both paths keep working. The PR is deployed now to the npm `beta` tag. 

I have manually tested it now too, but would you mind installing the beta tagged build from npm and confirming that both paths work for you now? You should be able to install it with `npm add serverless-aws-static-file-handler@beta`

FYI: I'll merge PR #34 to create 2.0.4 once I'm confident the beta-tagged version is working.

**Comment by katspaugh** [comment]
Yep, the old path works with the beta 👍

**Comment by activescott** [comment]
Thanks. I'll merge that to the latest tag here momentarily. Thank you again for reporting and for confirming!
